repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285  # Usá la última versión estable
    hooks:
      - id: ruff
        args: [--fix]  # Opcional, para que arregle automáticamente

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [ "types-requests", "types-PyYAML" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: poetry run pytest --maxfail=1 --disable-warnings -q
        language: system
        pass_filenames: false
